### ISSUE TITLE
Wiki example error

### ISSUE THREAD

**Issue by stempelo** [danielwilczak101/EasyGA#16]
In this example [https://github.com/danielwilczak101/EasyGA/wiki/Ways-to-Print](https://github.com/danielwilczak101/EasyGA/wiki/Ways-to-Print)

gives me this error
   ga.evolve(5)
TypeError: evolve() takes 1 positional argument but 2 were given

I don't understand, can you help me?

**Comment by danielwilczak101** [comment]
Hey!

Are you running the full example that you linked?

One misunderstanding I can see you having is running ga.evolve(5) by itself wont work.

If you want to change the amount of generations then an example of this would be.

```Python
import EasyGA

# Create the genetic algorithm
ga = EasyGA.GA()

# Chnage the ga attributes
ga.generation_goal     = 20

while ga.active():
    # Evolve only a certain number of generations
    ga.evolve(5)
    # Print the current generation
    ga.print_generation()
    # Print the best chromosome from that generations population
    ga.print_best_chromosome()
    # If you want to show each population
    #ga.print_population()
    # To divide the print to make it easier to look at
    print('-'*75)
```

Now if you want to run the whole thing at once. You can use the example below.

```Python
import EasyGA

# Create the genetic algorithm
ga = EasyGA.GA()

# Chnage the ga attributes
ga.generation_goal     = 20

# Evolve the genetic algorithm
ga.evolve()

# Print the current generation and population
ga.print_generation()
ga.print_population()
```

Let me know if this helps. I can go into more detail if you want.

**Comment by SimpleArt** [comment]
This issue is caused by using an old version of EasyGA, which used the now deprecated `ga.evolve_generations(5)` instead of `ga.evolve(5)`. A quick `pip install --upgrade EasyGA` should fix this issue.
