### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by AGZain** [danielwilczak101/EasyGA#17]
Hi there,

I'm using EasyGA to optimize parameters for a Keras LSTM. Over 20 generations and 10 chromosomes, I notice a RAM usage of over 13 GB. Each call to the fitness function really should not be using this much RAM, so I'm wondering if multiple calls to the fitness function are being done in parallel.

Does anyone have any insight on this matter?

**Comment by danielwilczak101** [comment]
Currently the fitness function is not running in parallel. Each call to the fitness function is run sequentially. We are currently working on async / multi processing functionality for the fitness function.

When it comes to memory it could be two things.

1. EasyGA stores all its data in a sqlite3 database file so this writing of each chromosome structure / fitness data could be taking a lot of your memory based on what your chromosome looks like.

Solution:
Add this line to your built ga before you start evolving.
```Python
# Dont save the population to the database
ga.save_data = False
```

2. This could be a parallel issue but like I said this feature is currently being developed. 

- If your very motivated. All the fitness function calls come from the same EasyGA.py file.

Were it runs:
```Python
# Update and sort fitnesses
self.set_all_fitness()
```

Function:
```Python
def set_all_fitness(self):
        """Will get and set the fitness of each chromosome in the population.
        If update_fitness is set then all fitness values are updated.
        Otherwise only fitness values set to None (i.e. uninitialized
        fitness values) are updated.
        """

        # Check each chromosome
        for chromosome in self.population:

            # Update fitness if needed or asked by the user
            if chromosome.fitness is None or self.update_fitness:
                chromosome.fitness = self.fitness_function_impl(chromosome)
```

Hopefully this helps.
