### ISSUE TITLE
How do I cite you?

### ISSUE THREAD

**Issue by fwollatz** [danielwilczak101/EasyGA#24]
I want to cite your project in my masterthesis. For that I would need some Information about you, but putting a bibtex-format citation on this could help in general, when your project is cited.

So far I would cite you like this (Edit: Adjusted it to the cff file!).

@misc{EasyGA,
title={EasyGA - Genetic Algorithms made Easy}, 
url={https://github.com/danielwilczak101/EasyGA/wiki}, 
author={Wilczak, Daniel and Nguyen, Jack}, 
year={2021},
month={May},
version={2.0.4},
note={Accessed: (2023-06-12)},
}

Do you have any wishes what should be changed?

**Comment by danielwilczak101** [comment]
Hey! Awesome to hear of your citation. We added a [citation.cff](https://github.com/danielwilczak101/EasyGA/blob/version1/CITATION.cff) file for users if they want to cite the package.

**Comment by fwollatz** [comment]
Awesome! Thanks! I adjusted my citation from above!
